### PR TITLE
fix: Generate Menu structure in scripts

### LINKED ISSUE #31: Move table creation logic from word doc to scripts
Currently the word doc has table headings only for each menu item category.
It is recommended to derive the complete structure from excel including the menu categories as well so we will be removing the table headings from word doc and creating the corresponding menu category divs from pos data.

For faster spinner rendering, the spinner has been created using auto-blocks.

The resulting word will look like [this](https://adobe-my.sharepoint.com/:w:/r/personal/shroti_adobe_com/_layouts/15/Doc.aspx?sourcedoc=%7B3B8352D0-3F83-4605-BED8-4768739F9BAC%7D&file=cafe-lite.docx&action=default&mobileredirect=true)

### PR DESCRIPTION
**Pull request by div8063**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #31 

- Removed headings from word doc so now menu structure is being created in scripts only
- Created Spinner through an auto-block for its faster loading

Test URLs:
- Before: [https://main--caesars-screens--hlxsites.hlx.live/screens/menus/cafe](https://main--caesars-screens--hlxsites.hlx.live/screens/menus/cafe)
- After: [https://issue-31--caesars-screens--hlxsites.hlx.live/screens/menus/cafe-lite](https://issue-31--caesars-screens--hlxsites.hlx.live/screens/menus/cafe-lite)

### CODE REVIEW

File: scripts/menu-content-parser.js [hunk 1]
```diff
@@ -71,12 +52,23 @@ function categoriseItems(menuData) {
   return itemsMap;
 }
 
+function addClassForSpecialItems(element, root) {
+  if (root && root.lastChild && root.lastChild.innerText
+      && root.lastChild.innerText.toLowerCase().includes(FRENCH_BAGUETTE)
+      && (element.innerText.toLowerCase().includes(HAM_AND_GRUYERE)
+      || element.innerText.toLowerCase().includes(VEGETARIAN)
+      || element.innerText.toLowerCase().includes(TURKEY_AND_SWISS))) {
+    element.id = 'french-baguette-items';
```
Comment (shrotia) [inline scripts/menu-content-parser.js:61]: Should we add 'french-baguette-items' as a Class, rather Id ?

Comment (div8063) [reply scripts/menu-content-parser.js:61]: Sure

**Review by shrotia — APPROVED** [review]
